### PR TITLE
Fix completion for borg-build and borg-activate.

### PR DESCRIPTION
**Pull request by thblt**
This commit allows to interactively build and activate clones as well as drones.  Previously, interactive completion for borg `borg-build` and `borg-activate` required a valid drone name as parameter.

### CODE REVIEW

**Comment by tarsius** [comment]
Thanks!

Please squash these commits and also use your real name as the author name (since you post your name on your homepage, I assume you are not opposed to that).

**Comment by thblt** [comment]
Should be good, I think. Please tell me if I forgot something/done something wrong. Thanks!

**Comment by tarsius** [comment]
So I actually had more than just a brief look now (I was quite busy with the Magit fundraiser and all)...

I don't consider this a "fix" but a possible change in behavior. These commands are intentionally limited to work only on drones not on any clone, the reasoning being that after cloning a package to review it you either assimilate it or else remove it.

Granted after cloning and inspecting the package you might also want to try it out before deciding to keep it, but even then its not really necessary that these commands operate on un-assimilated clones. If you end up removing the package, then `borg-assimilate` followed by `borg-remove` is fewer commands than `borg-build` and `borg-activate` followed by `borg-remove`. `borg-assimilate` does a bit more than `borg-build` and `borg-activate` do taken together, but `borg-remove` does undo most of that. So I don't really see what the benefit of calling these command separately might be.

What's a use-case that requires that `borg-build` and `borg-activate` operate on any clone?

**Comment by thblt** [comment]
Thanks for your reply, and congratulations about the kickstarter :)

The main use-case for me is indeed trying out non-assimilated packages before assimilating them or removing them.  

> Granted after cloning and inspecting the package you might also want to try it out before deciding to keep it, but even then its not really necessary that these commands operate on un-assimilated clones.

Actually, it's necessary that at least `borg-activate` works, since  `borg-clone` doesn't activate the package.   I don't know if this is a bug in `borg-clone` or intended behavior.

Beyond that, and for me at least, trying out a package may span across multiple Emacs sessions.  In this case, I need to manually reactivate the package at each session, since `borg-initialize` does nothing on non-assimilated packages.  

I haven't used  `borg-build` on clones, but one may want to checkout a different version than HEAD, or make changes to their clone while trying out a package, etc.

**Comment by tarsius** [comment]
I'll have to think about this some more but after reading your reply I am now more likely to do this.

**Comment by tarsius** [comment]
I have now implemented this in 66ffbf3f64b26c01bcb5516e05d203050bfacfd8, which I just pushed to `master`. The only real downside to adding this flexibility is that the `drone` argument of many functions had to be renamed to `clone`, which is a little unfortunate because in most cases they operate on actual drones, but it's not a big deal.

**Comment by thblt** [comment]
Thanks for accepting this.  Please, next time, don't hesitate to ask me to do the variable renaming/documentation update, unless of course you actually prefer doing it yourself.

**Comment by tarsius** [comment]
I am reopening this to test something completely unrelated.

**Pull request closed without merging**
