### PR TITLE
Fix typo.

### PR DESCRIPTION
**Pull request by whxvd**
The second pull request in my life. Now I am comfortable with them. I hope I did not bother you too much with too little. Thank you for what you are doing.

### CODE REVIEW

**Comment by tarsius** [comment]
Welcome to the active part of your FOSS live! That's no bother at all - thanks for your contribution.

Some experienced developers do end the summary line of commit messages with a period, but the majority does not. It's really a matter of taste, so you should follow the style used by the project you are contributing to - in this case by not ending it with a period. You can do that (using Magit) by editing the commit message using <kbd>c w</kbd> and then force-pushing using <kbd>P - f p</kbd>.

The reason that I prefer to not use a period is that I think of the summary as a heading, not as a sentence. While the summary line often forms a complete sentence, sjust as often it does not, and ending it with a period for the sake of consistency in such cases would be weird.

**Comment by whxvd** [comment]
I am still (de)assimilating from emacs.g down to a suitable starting point for me, which - for the time being - will not include e.g. epkg. When I finished that I will start to learn enough about Magit, until I understand what 

> editing the commit message using `c w` and then force-pushing using `P - f p`

means. I do have a strong guess about what it means in non-Ma and known-to-me git terms. But I want to learn Magit anyway.

It may take up to a week.

Thank you for the introduction and guidance!

**Comment by tarsius** [comment]
Take your time.

**Comment by tarsius** [comment]
You can also do so on the command-line, using:

```
git commit --amend -m "Fix typo"
git push --force-with-lease
```

I plan to create a release today or tomorrow, and will soon do this myself if you don't get around to it before then.

**Comment by whxvd** [comment]
Done.

**Comment by tarsius** [comment]
Thanks!

**Pull request merged**
